name: bmcs_env
channels:
- conda-forge
dependencies:
- appmode
- jupyter_contrib_nbextensions
- traits>=6.1.1
- matplotlib-base
- numpy
- sympy
- k3d
- ipywidgets
- ipympl
- ipytree
- k3d
- pip
- pip:
  - -e .
